$ANSIBLE_VAULT;1.1;AES256
63383138313164623333333531373362646465353432373466663634383337666536323034326161
3837613732653861303730633235616338343163326566360a376533643930393461356362353430
34326135336233373233366661666333306235623935643033346562396536663635663539613865
6466303535303163320a353065353763613431626137336563333466303535363930653933613066
37663833356531323533313333393138613264353735366132376461323536666131396339343535
3333666131396134643164666134613632386564373636623032
